config/routes.rb
HCEF::Application.routes.draw do

  resources :school_districts

  resources :after_schools
  match "/after_schools/update_by_id/:id" => "after_schools#update_by_id", via: :post
  match "/after_schools/update_sign_in_by_id/:id" => "after_schools#update_sign_in_by_id", via: :post
  match "/after_schools/load_data" => "after_schools#load_data", via: :post
  match "/master_view_new/submit" => "static#master_view_submit", via: :post
  get 'program/:id/:date' => "programs#show_day", as: "program_show_day"

  resources :programs
  resources :locations
  resources :schools
  resources :children
  resources :guardians
  resources :instructors
  resources :sessions
  resources :sub_locations
  resources :enrichments
  resources :field_trips

  resources :providers do
    member do
      put :toggle_activity
    end
  end

  get 'home' => 'static#beta'
  get 'master_view' => 'static#home'
  get 'master_view_new' => 'static#master_view_new'
  get 'admin_dash' => 'static#admin_dash', :as => :dash
  get "child/active/:id" => 'children#child_active', :as => :child_active
  get "instructor/active/:id" => 'instructors#instructor_active', :as => :instructor_active
  root :to => 'static#beta'

  get 'create_child' => 'static#create_child'

  #User routes (login, logout, signup...)
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get 'download_children' => 'static#download_children', :as => :download_children
  get 'download_programs' => 'static#download_programs', :as => :download_programs

  match '*post' => "errors#error_404", via: [:post, :get]

end

app/models/location.rb
class Location < ActiveRecord::Base
  # Relationships
  has_many :programs
  has_many :child_locations, dependent: :destroy
  has_many :children, through: :child_locations
  has_many :guardian_locations, dependent: :destroy
  has_many :guardians, through: :guardian_locations
  has_many :assignments, dependent: :destroy
  has_many :instructors, through: :assignments
  has_many :sub_locations, dependent: :destroy

  # Validations
  validates_presence_of :name

  # Scopes
  scope :alphabetical, -> { order("name") }

  # Callbacks
  before_destroy :make_children_inactive, :make_instructors_inactive

  # Makes children inactive if this is their only location
  def make_children_inactive
    for child in self.children do
      if !child.locations.nil? and child.locations.length <= 1
        child.active = false
        child.save!
      end
    end
  end

  # Makes instructors and therefore user inactive if this is their only location
  def make_instructors_inactive
    for instructor in self.instructors do
      if !instructor.locations.nil? and instructor.locations.length <= 1
        instructor.user.active = false
        instructor.user.save!
      end
    end
  end
end

app/models/program.rb
class Program < ActiveRecord::Base
  # Relationships
  belongs_to :location
  has_many :after_schools, dependent: :destroy
  has_many :enrichments, dependent: :destroy
  has_many :field_trips, dependent: :destroy
  has_many :enrollments, dependent: :destroy
  has_many :children, through: :enrollments

  accepts_nested_attributes_for :enrichments, reject_if: lambda { |enr| enr[:length].blank? }
  accepts_nested_attributes_for :field_trips, reject_if: lambda { |ft| ft[:length].blank? }

  # Validations
  validates_presence_of :name
  validates_presence_of :program_type
  validates_inclusion_of :program_type, in: %w( enrichment after_school field_trip) #Test case_sensitivity
  validates_presence_of :start_date #In case they're putting programs in from old years
  #validates_presence_of :end_date #on_or_after: :start_date

  # Scopes
  scope :alphabetical, -> { order("name") }
  scope :ascending, -> { order("start_date") }
  scope :descending, -> { order("start_date DESC") }
  scope :upcoming, -> { where("start_date > ?", Date.today) }
  scope :active, -> { where("end_date >= ?", Date.today) }
  scope :inactive, -> { where("end_date < ?", Date.today) }

  # Methods

  #this method shows children based on the location that they are assigned to
  def by_location(loc_id)
    children = []
    ChildLocation.all.each do |c|
      if c.location_id == loc_id and c.child.active == true
        children << c.child
      end
    end
    return children
  end

  #this method shows the overall average time of after school program
  def average_time
    homework_time = 0.0
    literacy_time = 0.0
    technology_time = 0.0
    reading_specialist_time = 0.0
    physical_time = 0.0
    hands_on_time = 0.0
    total_days = self.after_schools.count
    self.after_schools.each do |a|
      #just add 0 if the students time is nil for that particular activity
      homework_time += a.homework_time.try(:to_f) || 0.0
      literacy_time += a.literacy_time.try(:to_f)|| 0.0
      technology_time += a.technology_time.try(:to_f)|| 0.0
      reading_specialist_time += a.reading_specialist_time.try(:to_f) || 0.0
      physical_time += a.physical_activity.try(:to_f) || 0.0
      hands_on_time += a.hands_on_activity.try(:to_f) || 0.0
    end

    if total_days!=0
      return [["Homework", homework_time/total_days], ["Literacy", literacy_time/total_days], ["Technology", technology_time/total_days], ["Reading Specialist", reading_specialist_time/total_days], ["Physical Activity", physical_time/total_days], ["Hands On Time", hands_on_time/total_days]]
    else
      return [["Homework", 0], ["Literacy", 0], ["Technology", 0], ["Reading Specialist", 0], ["Physical Activity", 0], ["Hands On Time", 0]]
    end
  end

  #returns all days recorded in program for afterschool programs
  def program_days
    student_days=AfterSchool.for_program(self.id)
    days=student_days.group_by(&:date).sort
    dates=[]
    for i in 0..days.length-1
      dates << [days[i][0], days[i][1].count]
    end
    return dates
  end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :show_day, :edit, :update, :destroy]
  authorize_resource

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all.descending.paginate(:page => params[:page], :per_page => 10)
  end


  # GET /programs/1
  # GET /programs/1.json
  def show
    @average_times = @program.average_time
    #@days=AfterSchool.for_program(@program.id).ascending # old
    @days = AfterSchool.for_program(@program.id).ascending.group_by(&:date)
    if @program.program_days.count > 0
      @dates = @program.program_days.paginate(:page => params[:dates_page], :per_page => 2)
    end
    if !@program.field_trips.nil?
      @info = @program.field_trips.order(event_date: :desc).paginate(:page => params[:field_trips_page], :per_page => 10)
    end

    if !@program.enrichments.nil?
      @enrich_info = @program.enrichments.order(event_date: :desc).paginate(:page => params[:enrichments_page], :per_page => 10)
    end

    @children = @program.children.active.alphabetical.paginate(:page => params[:children_page], :per_page => 10)
  end

  def show_day
    @average_times = @program.average_time
    @days=AfterSchool.for_program(@program.id).for_date(params[:date].try(:to_date)).ascending
  end

  # GET /programs/new
  def new
    @program = Program.new

  end

  # GET /programs/1/edit
  def edit
    @children = @program.by_location(@program.location_id)
    @instructor = Instructor.all
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render action: 'show', status: :created, location: @program }
      else
        format.html { render action: 'new' }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:name, :program_type, :start_date, :end_date, :location_id, :child_ids => [])
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_day_summary.html.erb
<div class="table-responsive">
  <table class="table table-striped">
    <tr>
      <thead>
        <th>
          Date
        </th>
        <th>
          Day of Week
        </th>
        <th>
          Students Present
        </th>
        <th>
          View Day
        </th>

      </thead>
    </tr>
    <% if false and !@dates.nil? # Skip this section %>
      <% @dates.each do |d| %>
        <tr>
          <td><%= d[0] %></td>
          <td><%= d[0].strftime("%A") %></td>
          <td><%= d[1] %></td>
          <td>
            <button type="button" class="btn btn-default">
              <a href=<%= "/program/#{@program.id}/#{d[0]}"%>>Show Day<a>
            </button>
          </td>
        </tr>
      <% end %>
    <% end %>

    <% unless @days.blank? %>
      <% @days.each do |date,after_school_objects| %>
        <tr>
          <td><%= date %></td>
          <td><%= date.try(:strftime, "%A") %></td>
          <td><%= after_school_objects.count %></td>
          <td>
            <%= link_to "Edit", edit_after_school_path(after_school_objects.first),
              class: "btn btn-default" %>
            <%= link_to "Show Day", program_show_day_path(id: @program.try(:id), date: date.to_s(:iso_8601)),
              class: "btn btn-default" %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>
    <% if false and !@dates.nil? # Skip this section %>
      <%= will_paginate @dates, :param_name => 'dates_page' %>
    <% end %>
</div>

app/views/programs/_days.html.erb
<div class="container">
<div class="table-responsive">      
      <table class="table table-striped">
      <tr>
        <thead>
          <th>
            Date
          </th>
          <th>
            Student
          </th>
          <th>
            Tech Time
          </th>
          <th>
            Literature Time
          </th>
          <th>
            Homework Time
          </th>
          <th>
            Reading Time
          </th>
          <th>
            Physical Activity Time
          </th>
          <th>
            Hands On Time
          </th>
          <th>
            Total Minutes
          </th>
        </thead>
      </tr>
        <% @days.each do |d| %>
	      <tr>
	        <td><%= d.date %></td>
	        <td><%= d.child.name %></td>
	        <td><%= d.technology_time %></td>
	        <td><%= d.literacy_time %></td>
	        <td><%= d.homework_time %></td>
	        <td><%= d.reading_specialist_time %></td>
          <td><%= d.physical_activity %></td>
          <td><%= d.hands_on_activity %></td>
	        <td ><%= d.total_time %></td>
	      </tr>
	    <% end %>
      </table>
</div>
<a class="btn btn-default" href="<%= program_path(@program.id) %>" role="button"> Back</a>
<a class="btn btn-primary" href="<%= programs_url %>" role="button"> All Programs</a>

</br></br>
</div>

app/views/programs/_enrich_fields.html.erb
  <div>
      <%= f.label :length %></br>
      <%= f.text_field :length %>

      <p>
      <%= f.label :notes %></br>
      <%= f.text_area :notes %>
      </p>

      <p>
      <%= f.label :provider_id %></br>
      <%= f.collection_select :provider_id, Provider.active.all, :id, :name %>
      </p>

      <% if @program.program_type=="field_trip" %>
                  <h6> Field Trip Attendance </h6>
                  <% for child in @children %>
                    <%= check_box_tag "field_trip[child_ids][]", child.id, @program.children.include?(child), {id: child.id} %>
                    <label for="<%= child.id %>"><%= child.name %></label>
                    <br />
                  <% end  %>
      <% elsif @program.program_type=="enrichment" %>
                  <h6> Enrichment Attendance </h6>
                  <% for child in @children %>
                    <%= check_box_tag "enrichment[child_ids][]", child.id, @program.children.include?(child), {id: child.id} %>
                    <label for="<%= child.id %>"><%= child.name %></label>
                    <br />
                  <% end  %>
       <% end  %>

  </div>

app/views/programs/_enrichment_form.html.erb
<div class="row">
  <div class="col-lg-2">
  </div>
  <div class="col-lg-7">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <% if @program.program_type=="enrichment" %>
          <h4>Enrichment Program</h4>
        <% elsif @program.program_type=="field_trip" %>
          <h4>Field Trip Program</h4>
        <% end %>
      </div>
      <div class="panel-body">
        <%= nested_form_for(@program) do |f| %>
          <% if @program.errors.any? %>

              <h2><%= pluralize(@program.errors.count, 'error') %> prohibited this program from being saved:</h2>

              <ul>
              <% @program.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>

          <% end %>
            <div class="row">
              <div class="col-lg-6">
                <%= f.label :name %><br>
                <%= f.text_field :name %>
              <br /><br />

                <% if controller.action_name == "edit" and @program.program_type=="after_school" %>
                  <h6> Add Children to This Program </h6>
                  <% for child in @children %>
                    <%= check_box_tag "program[child_ids][]", child.id, @program.children.include?(child), {id: child.id} %>
                    <label for="<%= child.id %>"><%= child.name %></label>
                    <br />
                  <% end  %>
                  
                <% end  %>

                <% if controller.action_name == "edit" %>
                  <h6> Assign Instructor to This Program </h6>
                  <% for instructor in @instructor %>
                    <%= check_box_tag "program[instructor_ids][]", instructor.id, @program.instructors.include?(instructor), {id: instructor.id} %>
                    <label for="<%= instructor.id %>"><%= instructor.proper_name %></label>
                    <br />
                  <% end  %>
                <% end %><br /><br />
                <%= f.submit %>
            </div>
           
            
            <div class="col-lg-6">
              <% if @program.program_type=="enrichment" %>
                <%= f.fields_for :enrichment do |enrich| %>
                  <%= render :partial => "enrich_fields", :locals => { :f => enrich } %>
                <% end %>
              <% elsif @program.program_type=="field_trip" %>
                <%= f.fields_for :field_trip do |trip| %>
                  <%= render :partial => "enrich_fields", :locals => { :f => trip } %>
                <% end %>
              <% end %>
            </div>
           </div>
            
          </div>
        <% end %>
      </div>
    </div>
  <div class="col-lg-3">
  </div>
</div>

app/views/programs/_form.html.erb
<div class="row">
  <div class="col-lg-3">
  </div>
  <div class="col-lg-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h4>Program</h4>
      </div>
      <div class="panel-body">
        <%= form_for(@program, validate: true) do |f| %>
          <% if @program.errors.any? %>

              <h2><%= pluralize(@program.errors.count, 'error') %> prohibited this program from being saved:</h2>

              <ul>
              <% @program.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>

          <% end %>

              <%= f.label :name %><%= mark_required(@program, :name) %> <br>
              <%= f.text_field :name %>

              <br /><br />

              <% unless f.object.persisted? # Prevent editing program type after creation %>
                <%= f.label :program_type, 'Program Type' %><%= mark_required(@program, :program_type) %>
                <br />
                  <%= f.radio_button :program_type, 'after_school', :id => 'after_school', :checked => true %>
                  <%= f.label :program_type, 'After School', :for => 'after_school' %><br />
                  <%= f.radio_button :program_type, 'enrichment', :id => 'enrichment' %>
                  <%= f.label :program_type, 'Enrichment', :for => 'enrichment' %><br />
                  <%= f.radio_button :program_type, 'field_trip', :id => 'field_trip' %>
                  <%= f.label :program_type, 'Field Trip', :for => 'field_trip' %><br /><br />
              <% else %>
                <%= f.label :program_type, 'Program Type' %><br />
                <p><strong>The program type of an existing program may not be changed.</strong></p>
              <% end %>

              <%= f.label :start_date, 'Start Date', :for => 'start_date' %><%= mark_required(@program, :start_date) %>
              <br />
              <%= f.text_field :start_date, :id=> 'start_date', :class => 'datepick' %></br>

              <br />

              <%= f.label :end_date, 'End Date', :for => 'end_date' %><%= mark_required(@program, :end_date) %>
              <br />
              <%= f.text_field :end_date, :id=> 'end_date', :class => 'datepick' %>


              <br /><br />
              <%= f.label :location_id %><%= mark_required(@program, :location_id) %>
              <br />
              <%= collection_select(:program, :location_id, Location.alphabetical, :id, :name, prompt: true) %>
                <% if controller.action_name == "edit" %>
                  <h6> Add Children to This Program </h6>
                  <input type="checkbox" name="select_all" id="select_all" value="select_all"> Select All</input></br>
                  <% for child in @children %>
                    <%= check_box_tag "program[child_ids][]", child.id, @program.children.include?(child), {id: child.id} %>
                    <label for="<%= child.id %>"><%= child.name %></label>
                    <br />
                  <% end %>
                  <br /><br />
                <% end %>
              <br />
              <br />
              <br />
            <%= f.submit class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-lg-3">
  </div>
</div>

app/views/programs/edit.html.erb
<%= render 'form' %>

app/views/programs/index.html.erb
<ol class="breadcrumb">
  <li><a href="<%= home_path %>">Home</a></li>
</ol>

<h1>Programs </h1>

<div class="table-responsive">
  <table class='table table-striped'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Program type</th>
        <th>Start date</th>
        <th>End date</th>
        <th>Location</th>
        <th>Total Enrolled</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @programs.each do |program| %>
        <% if can? :read, program %>
          <tr>
            <td><%= link_to program.name, program_path(program) %></td>
          <td><%= program.program_type == "after_school" ? "After School" : program.program_type == "enrichment" ? "Enrichment" : "Field Trip" %></td>
            <td><%= program.start_date %></td>
            <td><%= program.end_date == "" ? "None" : program.end_date %></td>
            <td><%= program.location.nil? ? "None" : program.location == "" ? "None" : program.location.name %></td>
            <td><%= program.children.active.count %></td>
            <td><a class="btn btn-warning" href="<%= edit_program_path(program) %>" role="button"> Edit</a></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

  <br>
<% if can? :create, Program %> 
  <a class="btn btn-primary" href="<%= new_program_path %>" role="button"> New Program </a>
<% end %>

<%= will_paginate @programs %>

app/views/programs/new.html.erb
<%= render 'form' %>

app/views/programs/show.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><a href="<%= home_path %>">Home</a></li>
    <li><a href="<%= programs_url %>">Programs</a></li>
  </ol>
</br></br>


<% if @program.program_type=="after_school" %>
<div class="panel panel-primary">
    <div class="panel-heading">
      <h3 align="center"><%= @program.name %></h3>
    </div>

<div class="table-responsive">
      <table class="table table-condensed">
      <thead>
        <tr class="info">

            <th>
              Type
            </th>
            <th>
              Start date
            </th>
            <th>
              End date
            </th>
            <th>
              Children
            </th>
            <th>
              Location
            </th>
        </tr>
      </thead>
        <tr>
          <td><%= @program.program_type == "after_school" ? "After School" : @program.program_type == "enrichment" ? "Enrichment" : "Field Trip" %></td>
          <td><%= @program.start_date %></td>
          <td><%= @program.end_date %></td>
          <td><%= @program.children.active.count %></td>
          <td><%= @program.location.nil? ? "None" : @program.location == "" ? "None" : @program.location.name %></td>
        </tr>
      </table>
</div>


</div>

<% else %>
<div class="row">
        <div class="col-lg-3 col-sm-12">
          <div class="panel panel-info">
            <div class="panel-heading">Program Name</div>
            <div class="panel-body">
              <%= @program.name %>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-lg-offset-1 col-sm-12">
          <div class="panel panel-info">
            <div class="panel-heading">Type</div>
            <div class="panel-body">
              <%= @program.program_type == "after_school" ? "After School" : @program.program_type == "enrichment" ? "Enrichment" : "Field Trip" %>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-lg-offset-1 col-sm-12">
          <div class="panel panel-info">
            <div class="panel-heading">Location</div>
            <div class="panel-body">
              <%= @program.location.name  %>
            </div>

          </div>
        </div>
      </div>
<% end %>

    </br></br>
    <% if @program.program_type=="after_school" %>
        </br></br>
        <h5><u> Average Activity Time for All Children </u></h5>
        <%= bar_chart @average_times, colors: ["orange"] %>

      </br>
      <div class='row'>
        <div class='col-xs-12 col-sm-9'>
          <% if @days.nil? %>
            <h5 align="center">No days recorded for this program</h5>
          <% else %>
            <h5 align="center"> Daily Attendance/Time Allocation </h5>
            </br>
            <%= render :partial => "day_summary", :locals => { :days => @days } %>
            </br>
          <% end %>
        </div>
        <!-- Display children -->
        <div class='col-sm-3'>
          <% if @children.nil? or @children.count == 0 %>
            <h5>No children assigned to this program</h5>
          <% else %>
            <h4>Children</h4>
            <%= render :partial => '/children/list_children', :locals => {:children => @children} %>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 align="center">Attendance and Info</h3>
        </div>

<div class="table-responsive">
          <table class="table table-condensed">
          <thead>
            <tr class="info">

                <th>
                  Date
                </th>
                <th>
                  Provider
                </th>
                <th>
                  Notes
                </th>
                <th>
                  Length
                </th>
                <th>
                  Attendance
                </th>
                <th>
                  Actions
                </th>
            </tr>
          </thead>
          <% if @program.program_type=="field_trip" %>
            <% @info.each do |i| %>
              <tr>
                <td><%= i.event_date.try(:to_s) %></td>
                <td><%= i.provider.name %></td>
                <td><%= i.notes %></td>
                <td><%= i.length %></td>
                <td><%= "#{i.children.count}/#{@program.children.active.count}" %></td>
                <td><%= link_to("Edit", edit_field_trip_path(i)) if can? :edit, i %></td>
              </tr>
            <% end %>
          <% else %>
            <% @enrich_info.each do |i| %>
              <tr>
                  <td><%= i.event_date.try(:to_s) %></td>
                  <td><%= i.provider.name %></td>
                  <td><%= i.notes %></td>
                  <td><%= i.length %></td>
                  <td><%= "#{i.children.count}/#{@program.children.active.count}" %></td>
                  <td><%= link_to "Edit", edit_enrichment_path(i) if can? :edit, i %></td>
                </tr>
            <% end %>
          <% end %>
          </table>
</div>
        <% if @program.program_type=="field_trip" %>
          <%= will_paginate @info, :param_name => 'field_trips_page' %>
        <% elsif @program.program_type=="enrichment" %>
          <%= will_paginate @enrich_info, :param_name => 'enrichments_page' %>
        <% end %>
        </div>



    <% end %>

      <% if @program.program_type=="after_school" %>
        <a class="btn btn-primary" href="<%= new_after_school_path(program_id: @program.id) %>" role="button"> New Day</a>
      <% elsif @program.program_type=="enrichment" %>
        <a class="btn btn-primary" href="<%= new_enrichment_path(program_id: @program.id) %>" role="button">New Enrichment</a>
      <% else %>
        <a class="btn btn-primary" href="<%= new_field_trip_path(program_id: @program.id) %>" role="button">New Field Trip</a>
      <% end %>
      <a class="btn btn-info" href="<%= edit_program_path(@program) %>" role="button"> Edit Program</a>
      <a class="btn btn-default" href="<%= programs_url %>" role="button"> All Programs</a></br></br>
</div>

app/views/programs/show_day.html.erb
<ol class="breadcrumb">
    <li><a href="<%= home_path %>">Home</a></li>
    <li><a href="<%= programs_url %>">All Programs</a></li>
    <li><a href="<%= program_path(@program) %>"><%= @program.name %></a></li>
</ol>

<h2 align="center"><%= @program.name %></h2>

<div class="panel panel-warning">
      
      <table class="table table-condensed">
      <div class="panel-heading">
        <tr>
          <thead>
            <th>
              Type
            </th>
            <th>
              Start date
            </th>
            <th>
              End date
            </th>
            <th>
              Children
            </th>
            <th>
              Location
            </th>
          </thead>
        </tr>
      </div>
      <div class="panel-body">
        <tr>
          <td><%= @program.program_type == "after_school" ? "After School" : @program.program_type == "enrichment" ? "Enrichment" : "Field Trip" %></td>
          <td><%= @program.start_date %></td>
          <td><%= @program.end_date %></td>
          <td><%= @program.children.count %></td>
          <td><%= @program.location.nil? ? "None" : @program.location == "" ? "None" : @program.location.name %></td>
        </tr>
      </table>
    </div>
</div>

    </br></br>


      <h5 align="center"> Daily Attendance/Time Allocation </h5>
      </br>
      <%= render :partial => "days" %>
      </br>

</div>