config/routes.rb
HCEF::Application.routes.draw do

  resources :school_districts

  resources :after_schools
  match "/after_schools/update_by_id/:id" => "after_schools#update_by_id", via: :post
  match "/after_schools/update_sign_in_by_id/:id" => "after_schools#update_sign_in_by_id", via: :post
  match "/after_schools/load_data" => "after_schools#load_data", via: :post
  match "/master_view_new/submit" => "static#master_view_submit", via: :post
  get 'program/:id/:date' => "programs#show_day", as: "program_show_day"

  resources :programs
  resources :locations
  resources :schools
  resources :children
  resources :guardians
  resources :instructors
  resources :sessions
  resources :sub_locations
  resources :enrichments
  resources :field_trips

  resources :providers do
    member do
      put :toggle_activity
    end
  end

  get 'home' => 'static#beta'
  get 'master_view' => 'static#home'
  get 'master_view_new' => 'static#master_view_new'
  get 'admin_dash' => 'static#admin_dash', :as => :dash
  get "child/active/:id" => 'children#child_active', :as => :child_active
  get "instructor/active/:id" => 'instructors#instructor_active', :as => :instructor_active
  root :to => 'static#beta'

  get 'create_child' => 'static#create_child'

  #User routes (login, logout, signup...)
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get 'download_children' => 'static#download_children', :as => :download_children
  get 'download_programs' => 'static#download_programs', :as => :download_programs

  match '*post' => "errors#error_404", via: [:post, :get]

end

app/models/instructor.rb
class Instructor < ActiveRecord::Base

	has_one :user, dependent: :destroy
	has_many :assignments, dependent: :destroy
	has_many :locations, through: :assignments
	
	accepts_nested_attributes_for :user, reject_if: lambda { |user| user[:username].blank? or user[:password].blank? }

	validates :first_name, presence: true
	validates :last_name, presence: true

	scope :alphabetical, -> { order('last_name', 'first_name')}
	scope :active, -> {joins(:user).where("active = ?", true)}


	def name
		"#{self.last_name}, #{self.first_name}"
	end

	def proper_name
		"#{self.first_name} #{self.last_name}"
	end

	def is_active
		return true if self.user.active
		return false
	end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy, :instructor_active]
  authorize_resource

  def index
  	@instructors = Instructor.active.alphabetical
  end

  def show
  end

  def new
  	@instructor = Instructor.new
  	@instructor.build_user
  	@locations = Location.all
  end

  def edit
  	if @instructor.user.nil?
        @instructor.build_user
    end
  end

  def create
		@instructor = Instructor.new(instructor_params)
		respond_to do |format|
		  #this part checks to see if instructor was assigned a location, which is mandatory if their role is instructor, not admin
		  if @instructor.user.role == 'instructor' && params[:instructor][:location_ids].nil? 
		  	@instructor.errors.add(:base, "Instructor needs to be assigned to at least 1 location")
		  	format.html { render action: 'new' }
		  	format.json { render json: @instructor.errors.full_messages, status: :unprocessable_entity}
	      elsif @instructor.save
	        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
	        format.json { render action: 'show', status: :created, location: @instructor }
	      else
	        format.html { render action: 'new' }
	        format.json { render json: @instructor.errors.full_messages, status: :unprocessable_entity }
	      end
    	end
	end

  def update
    if @instructor.user.role == 'instructor' && params[:instructor][:location_ids].nil? 
      @instructor.errors.add(:base, "Instructor needs to be assigned to at least 1 location")
      render action: 'edit'
    elsif @instructor.update(instructor_params)
      # Make instructor active if they have one or more locations
      if @instructor.locations.length > 0
        if !@instructor.is_active
          @instructor.user.active = true
          @instructor.user.save!
        end
      end

      redirect_to @instructor, notice: "#{@instructor.name} has been updated"
    else
      render action: 'edit'
    end
  end

	def destroy
		@instructor.destroy
		redirect_to dash_path, notice: "#{@instructor.name} has been deleted"
	end

	def instructor_active
	  	if @instructor.user.active==true
	  		@instructor.user.active=false
	  		@instructor.user.save
	  		redirect_to dash_path, notice: "#{@instructor.name} was made inactive"
	  	else
	  		@instructor.user.active=true
	  		@instructor.user.save
	  		redirect_to dash_path, notice: "#{@instructor.name} was made active"
	  	end
	end

	private

		def set_instructor
			@instructor = Instructor.find(params[:id])
		end

		def instructor_params
			params.require(:instructor).permit(:first_name, :last_name, :location_ids => [], user_attributes: [:id, :username, :password, :password_confirmation, :role])
		end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<div class="row">
  <div class="col-lg-3">
  </div>
  <div class="col-lg-6">
    <div class="panel-heading">
      <h3>Instructor</h3>
    </div>
    <div class="panel-body">
      <div class="well well-lg">
        <%= form_for(@instructor, validate: true) do |f| %>
          <% if @instructor.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

            <ul>
              <% @instructor.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
          <% end %>
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12">
              <label>First Name</label><%= mark_required(@instructor, :first_name) %><br />
              <%= f.text_field :first_name %>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12">
              <label>Last Name</label><%= mark_required(@instructor, :last_name) %><br />
              <%= f.text_field :last_name %>
            </div>
          </div>	
          </br>
          <%= f.fields_for :user do |users| %>
            <%= render :partial => "user_form", :locals => { :f => users } %>
            <% end %>
          <br />
          <%if can? :manage, Location%>
            <h5><b>Assign Instructor to Location</b>*<%#= mark_required(@instructor, :location_ids %></h5>
            <p>
              <% for location in Location.all %>
                <%= check_box_tag "instructor[location_ids][]", location.id, @instructor.locations.include?(location), {id: location.id} %>
                <label for="<%= location.id %>"><%= location.name %></label>
                <br />
              <% end %>
            <% end %>
          </p>
          <br /><br />
          <button class="" type="submit" name="action">Submit</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/instructors/_user_form.html.erb
<div class="row">
  <div class="col-lg-4">
    <label for="icon_prefix">Username</label><%= mark_required(@instructor.user, :username) %><br />
    <%= f.text_field :username %>
  </div>
  <div class="col-lg-4">	
    <label for="icon_prefix">Password</label><%= mark_required(@instructor.user, :password) %><br />
    <%= f.password_field :password %>
  </div>

  <div class="col-lg-4">
    <label for="icon_prefix">Confirm</label><%= mark_required(@instructor.user, :password_confirmation) %><br />
    <%= f.password_field :password_confirmation %>	
  </div>
</div>
</br>
<% if can? :create, User %>
  <label>Role</label><%= mark_required(@instructor.user, :role) %><br />
    <%= f.select :role, User::ROLES, :prompt => "Select Role" %>
<% end %>

app/views/instructors/_users.html.erb
asdf

app/views/instructors/edit.html.erb
<%= render :partial => "form" %>

app/views/instructors/index.html.erb
<h1 class="">Instructors</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th data-field="name">Name</th>
    </tr>
  </thead>

  <tbody>
  <% if !@instructors.empty? %>
    <% @instructors.each do |instructor| %>
      <tr>
        <% if can? :read, instructor %>
          <td><%= link_to instructor.first_name + " " + instructor.last_name, instructor_path(instructor) %></td>
          <% if can? :update, instructor %>
            <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
          <% end %>
        <% end %>
    </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<br><br>

<button  type="button" class="btn btn-default">
<%= link_to 'New Instructor', new_instructor_path %>
</button></br></br>

app/views/instructors/new.html.erb
<%= render :partial => "form" %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @instructor.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @instructor.last_name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @instructor.user.role %>
</p>
<% if @instructor.user.role != "admin" %>
	<p>
	  <strong>Assigned Programs:</strong>
	  <table class='table table-striped'>
	    <thead>
	      <tr>
	        <th>Name</th>
	        <th>Program type</th>
	        <th>Start date</th>
	        <th>End date</th>
	        <th>Location</th>
	        <th></th>
	        <th></th>
	        <th></th>
	      </tr>
	    </thead>

	    <tbody>
	      <% @instructor.locations.each do |location| %>
	      	<% location.programs.each do |program| %>
		        <% if can? :read, program %>
		          <tr>
		            <td><%= link_to program.name, program_path(program) %></td>
		            <td><%= program.program_type == "after_school" ? "After School" : program.program_type == "enrichment" ? "Enrichment" : "Field Trip" %></td>
		            <td><%= program.start_date %></td>
		            <td><%= program.end_date == "" ? "None" : program.end_date %></td>
		            <td><%= program.location.nil? ? "None" : program.location == "" ? "None" : program.location.name %></td>
		            <% if can? :edit, program %>
		            	<td><%= link_to 'Edit', edit_program_path(program) %></td>
		            <% end %>
		          </tr>
		        <% end %>
		    <% end %>
	      <% end %>
	    </tbody>
	  </table>
	</p>
<% end %>
<% if can? :edit, @instructor %>
	<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<% end %>
<%= link_to 'Back', instructor_path %>