config/routes.rb
HCEF::Application.routes.draw do

  resources :school_districts

  resources :after_schools
  match "/after_schools/update_by_id/:id" => "after_schools#update_by_id", via: :post
  match "/after_schools/update_sign_in_by_id/:id" => "after_schools#update_sign_in_by_id", via: :post
  match "/after_schools/load_data" => "after_schools#load_data", via: :post
  match "/master_view_new/submit" => "static#master_view_submit", via: :post
  get 'program/:id/:date' => "programs#show_day", as: "program_show_day"

  resources :programs
  resources :locations
  resources :schools
  resources :children
  resources :guardians
  resources :instructors
  resources :sessions
  resources :sub_locations
  resources :enrichments
  resources :field_trips

  resources :providers do
    member do
      put :toggle_activity
    end
  end

  get 'home' => 'static#beta'
  get 'master_view' => 'static#home'
  get 'master_view_new' => 'static#master_view_new'
  get 'admin_dash' => 'static#admin_dash', :as => :dash
  get "child/active/:id" => 'children#child_active', :as => :child_active
  get "instructor/active/:id" => 'instructors#instructor_active', :as => :instructor_active
  root :to => 'static#beta'

  get 'create_child' => 'static#create_child'

  #User routes (login, logout, signup...)
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get 'download_children' => 'static#download_children', :as => :download_children
  get 'download_programs' => 'static#download_programs', :as => :download_programs

  match '*post' => "errors#error_404", via: [:post, :get]

end

app/views/partials/_flash.html.erb
<div class="container">
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>
</div>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style='border-top:none; box-shadow:none;'> -->
      <div class='navbar-header'>
        <a class="navbar-brand" href="/" style='background-color: #FFF; margin-left: -30px;'>
          <img src= <%= asset_path('logo.png') %> alt='Home' style='max-height: 50px;'>
        </a>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-this">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
      </button>
      </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-collapse collapse" id='collapse-this'>
      <ul class="nav navbar-nav">
        <% if !current_user.nil? %>
          <% if can? :read, Program %>
            <li><%= link_to "Programs", programs_url %></li>
          <% end %>
          <% if can? :create, Child %>  
            <li><%= link_to "Add Content", new_child_path %></li>
          <% end %>
          <% if can? :manage, Program %>  
            <li><%= link_to "Dash", dash_path %></li>
          <% end %>
          <% if can? :manage, Program %>  
            <li><%= link_to "Data Analysis", master_view_new_path %></li>
          <% end %>
        <% end %>
      </ul>

      <% if logged_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <p id='nav-username' class='navbar-text'> 
            <%= current_user.username %> &nbsp
            <%= link_to '(Logout)', logout_path %>
          </p>
        </li>
      </ul>
      <% else %>
        <p class='navbar-text navbar-right'><%= link_to 'Login', login_path %></p>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>