config/routes.rb
HCEF::Application.routes.draw do

  resources :school_districts

  resources :after_schools
  match "/after_schools/update_by_id/:id" => "after_schools#update_by_id", via: :post
  match "/after_schools/update_sign_in_by_id/:id" => "after_schools#update_sign_in_by_id", via: :post
  match "/after_schools/load_data" => "after_schools#load_data", via: :post
  match "/master_view_new/submit" => "static#master_view_submit", via: :post
  get 'program/:id/:date' => "programs#show_day", as: "program_show_day"

  resources :programs
  resources :locations
  resources :schools
  resources :children
  resources :guardians
  resources :instructors
  resources :sessions
  resources :sub_locations
  resources :enrichments
  resources :field_trips

  resources :providers do
    member do
      put :toggle_activity
    end
  end

  get 'home' => 'static#beta'
  get 'master_view' => 'static#home'
  get 'master_view_new' => 'static#master_view_new'
  get 'admin_dash' => 'static#admin_dash', :as => :dash
  get "child/active/:id" => 'children#child_active', :as => :child_active
  get "instructor/active/:id" => 'instructors#instructor_active', :as => :instructor_active
  root :to => 'static#beta'

  get 'create_child' => 'static#create_child'

  #User routes (login, logout, signup...)
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get 'download_children' => 'static#download_children', :as => :download_children
  get 'download_programs' => 'static#download_programs', :as => :download_programs

  match '*post' => "errors#error_404", via: [:post, :get]

end

app/models/after_school.rb
class AfterSchool < ActiveRecord::Base
  # Relationships
  belongs_to :program
  belongs_to :child

  # Validations
  validates_presence_of :date
  validates_date :date, allow_nil: false
  validates_presence_of :time_in
  validates_presence_of :time_out
  #validates_format_of :time_in, with: /[0-9]{1,4}/[0-9]{1,2}/[0-9]{1,2} [0-9]{1,2}:[0-9]{1,2}:[0-9]{1,2}/, :allow_nil => false, :allow_blank => false
  #validates_format_of :time_out, with: /[0-9]{1,4}/[0-9]{1,2}/[0-9]{1,2} [0-9]{1,2}:[0-9]{1,2}:[0-9]{1,2}/, :allow_nil => false, :allow_blank => false
  #validates :time_out, after: :time_in
  validates_numericality_of :total_minutes, greater_than_or_equal_to: 0
=begin
  validates_time :homework_time,
  :literacy_time
  :technology_time
=end

  # Scopes
  scope :ascending, -> { order("date") }
  scope :descending, -> { order("date DESC") }
  scope :for_program, ->(program_id) { where("program_id = ?", program_id)}
  scope :for_date, ->(date) { where("date = ?", date)}

  #calculates the total time for one after school day
  def total_time
    times = [self.reading_specialist_time, self.technology_time, self.homework_time, self.literacy_time, self.physical_activity, self.hands_on_activity]

    total = 0
    times.each do |t|
      if !t.nil?
        total += t
      end
    end
    return total
  end

end

app/models/school.rb
class School < ActiveRecord::Base
	#relationships
	has_many :children
	belongs_to :school_district

	#validations
	validates_presence_of :name
end

app/controllers/after_schools_controller.rb
class AfterSchoolsController < ApplicationController
  before_action :set_after_school, only: [:show, :edit, :update, :destroy]
  # Turn off protect_from_forgery for these actions
  protect_from_forgery :except => [:update_by_id, :update_sign_in_by_id, :load_data]
  authorize_resource

  def index
    @after_schools = AfterSchool.all
  end

  def show
  end

  def new
    @program_id = params[:program_id]
    @program = Program.find(@program_id)
    @after_school = AfterSchool.new
    @data = []
    @data_sign_in = []
    @children = @program.children.active
    @children_ids = []
    for child in @children
      @data.push([child.name] + [0]*6 + [""] + [""])
      @data_sign_in.push([child.name] + [""] + [""])
      @children_ids.push(child.id)
    end
    if cannot? :read, @program
      redirect_to "public/404.html"
    end
  end

  def edit
    @program = @after_school.program
    @program_id = @program.try(:id)
    @data = []
    @data_sign_in = []
    @children = @program.children.active
    @children_ids = []
    for child in @children
      @data.push([child.name] + [0]*6 + [""] + [""])
      @data_sign_in.push([child.name] + [""] + [""])
      @children_ids.push(child.id)
    end
    if cannot? :read, @program
      redirect_to "public/404.html"
    end
  end

  def create
    @after_school = AfterSchool.new(after_school_params)
    if @after_school.save
      redirect_to @after_school, notice: "#{@after_school.date} was successfully created."
    else
      render action: "new"
    end
  end

  def update
    if @after_school.save
      redirect_to @after_school, notice: "#{@after_school.date} has been updated."
    else
      render action: "edit"
    end
  end

  def update_by_id
    program_id = params["program_id"]
    child_id = params[:id]
    date = Date.strptime(params["date"],"%m/%d/%Y")
    col = params["col"]
    value = params["value"]

    @after_school = AfterSchool.find_or_initialize_by(program_id: program_id, child_id: child_id, date: date)
    # Note on methods:
    # update_attribute does NOT validate
    # update           does validate
    case col
    when 1
      @after_school.update_attribute(:homework_time, value)
    when 2
      @after_school.update_attribute(:literacy_time, value)
    when 3
      @after_school.update_attribute(:technology_time, value)
    when 4
      @after_school.update_attribute(:reading_specialist_time, value)
    when 5
      @after_school.update_attribute(:physical_activity, value)
    when 6
      @after_school.update_attribute(:hands_on_activity, value)
    when 7
      @after_school.update_attribute(:goal, value)
    when 8
      @after_school.update_attribute(:notes, value)
    end

    # Don't need to return anything
    head :ok
  end

  def update_sign_in_by_id
    program_id = params["program_id"]
    child_id = params[:id]
    date = Date.strptime(params["date"],"%m/%d/%Y")
    col = params["col"]
    value = params["value"]
    puts value
    time = toMilitaryTime(value)

    @after_school = AfterSchool.find_or_initialize_by(program_id: program_id, child_id: child_id, date: date)
    # Note on methods:
    # update_attribute does NOT validate
    # update           does validate
    case col
    when 3 # time in changed
      @after_school.update_attribute(:time_in, time)
      if !@after_school.time_out.nil?
        total_minutes = ((@after_school.time_out - @after_school.time_in) / 60).to_i # minutes
        #TODO migrate total_hours => total_minutes
        if total_minutes > 0
          @after_school.update_attribute(:total_hours, total_minutes)
        end
      end
    when 4 # time out changed
      @after_school.update_attribute(:time_out, time)
      # update totalHours
      if !@after_school.time_in.nil?
        total_minutes =( (@after_school.time_out - @after_school.time_in) / 60).to_i # minutes
        if total_minutes > 0
          @after_school.update_attribute(:total_hours, total_minutes)
        end
      end
    end
    # Don't need to return anything
    head :ok
  end

  def load_data
    data = params["data"]
    data_sign_in = params["data_sign_in"]
    program_id = params["program_id"]
    children_ids = params["children_ids"]
    date = Date.strptime(params["date"],"%m/%d/%Y")
    if children_ids.nil?
      data = []
      data_sign_in = []
    else
      # Look at every child to check if a record exists
      for index in 0..children_ids.count-1
        child_id = children_ids[index]
        record = AfterSchool.where(:program_id=>program_id).where(:child_id=>child_id).where(:date=>date).first

        # If the record exists, give the row this data
        if !record.nil?

          if record.homework_time.nil?
            data[index][1] = 0
          else
            data[index][1] = record.homework_time
          end
          if record.literacy_time.nil?
            data[index][2] = 0
          else
            data[index][2] = record.literacy_time
          end
          if record.technology_time.nil?
            data[index][3] = 0
          else
            data[index][3] = record.technology_time
          end
          if record.reading_specialist_time.nil?
            data[index][4] = 0
          else
            data[index][4] = record.reading_specialist_time
          end
          if record.physical_activity.nil?
            data[index][5] = 0
          else
            data[index][5] = record.physical_activity
          end
          if record.hands_on_activity.nil?
            data[index][6] = 0
          else
            data[index][6] = record.hands_on_activity
          end
          if record.goal.nil?
            data[index][7] = ""
          else
            data[index][7] = record.goal
          end
          if record.notes.nil?
            data[index][8] = ""
          else
            data[index][8] = record.notes
          end

          if record.time_in.nil?
            data_sign_in[index][3] = ""
          else
            hour = record.time_in.hour
            minute = record.time_in.min
            time = toStandardTime(hour, minute)
            data_sign_in[index][3] = time
          end
          if record.time_out.nil?
            data_sign_in[index][4] = ""
          else
            hour = record.time_out.hour
            minute = record.time_out.min
            time = toStandardTime(hour, minute)
            data_sign_in[index][4] = time
          end

        # If the record doesn't exist, set the row to initial, zero'd values
        else
          data[index] = [data[index][0]] + [0]*6 + [""] + [""]

          data_sign_in[index][3] = ""
          data_sign_in[index][4] = ""
        end
      end
    end

    render :json => {data: data, data_sign_in: data_sign_in}
    end

  def destroy
    @after_school.destroy
    redirect_to after_schools_url, notice: "#{@after_school.date} has been destroyed"
  end

  private
    # Expects string input "hh:mm pm"
    def toMilitaryTime(time)
      hour = time.split(':', 2)[0].to_i
      minute = time.split(':', 2)[1].split(" ", 2)[0].to_i
      meridiem = time.split(' ', 2)[1]
      if meridiem.nil?
        meridiem = 'am' if time.include?('am')
        meridiem = 'pm' if time.include?('pm')
      end
      hour = 0 if meridiem == 'am' && hour == 12   # 12am goes to 0
      hour += 12 if meridiem == 'pm' && hour != 12 # 12pm stays
      minute = "0#{minute}" if minute < 10 # Leading zero
      return hour.to_s + ":" + minute.to_s
    end
    def toStandardTime(hour, minute)
      hour = hour.to_i
      minute = minute.to_i
      meridiem = hour < 12 ? 'am' : 'pm'
      hour = hour % 12
      hour = 12 if hour.zero? # 0 hour becomes 12am
      minute = "0#{minute}" if minute < 10 # Leading zero
      return hour.to_s + ':' + minute.to_s + ' ' + meridiem
    end

    def set_after_school
      @after_school = AfterSchool.find(params[:id])
    end

    def after_school_params
      params.require(:after_school).permit(:program_id, :child_id, :date, :time_in, :time_out, :total_hours, :homework_time, :literacy_time, :technology_time, :reading_specialist_time, :physical_activity, :hands_on_activity, :goal, :notes)
    end
end

app/helpers/after_schools_helper.rb
module AfterSchoolsHelper
end

app/views/after_schools/_form.html.erb
<%= form_for(@after_school, validate: true) do |f| %>
  <% if @after_school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@after_school.errors.count, "error") %> prohibited this After School Form from being saved:</h2>

      <ul>
      <% @after_school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='row'>
    <div class='col-md-12 text-center'>
    <%= f.label :date, 'Date', :for => 'date' %><br />

    <%= f.text_field :date, :id=> 'date', :class => 'datepick', :placeholder => "Select Date*",
      disabled: (f.object.persisted? ? true : false) %>
    </div>
  </div>
  <div id='toggleTables'>
    <div class='row'>
      <div class='col-md-12 text-center'>
        <div id='button' class='btn-group' role='group'>
          <button type='button' class='custom_btn btn btn-default active' onclick='return showHotSignIn()'>Sign-in</button>
          <button type='button' class='custom_btn btn btn-default' onclick='return showHot()'>Daily Log</button>
        </div>
      </div>
    </div>
    <!-- Start hot -->
    <div class='row'>
      <div class='col-md-12 text-center'>
        <div id='hot'></div>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-12 text-center'>
        <div id='hot_sign_in'></div>
      </div>
    </div>
  </div>
  <br /><br />
    <script>
      var data = <%= raw @data.to_json %>;
      var data_sign_in = <%= raw @data_sign_in.to_json %>;
      var children_ids = <%= raw @children_ids.to_json %>;
      var program_id = <%= raw @program_id %>;
    </script>
<!-- End hot -->

<a class="btn btn-primary" href="<%= program_path(@program) %>" role="button"> Create </a>
<a class="btn btn-danger" href="<%= programs_url %>" role="button"> Cancel </a>

<% end %>

app/views/after_schools/edit.html.erb
<h1>Editing After School Day</h1>

<%= render 'form' %>

app/views/after_schools/index.html.erb
<h1>Listing after_schools</h1>

<table>
  <thead>
    <tr>
      <th>Program</th>
      <th>Guardian</th>
      <th>Date</th>
      <th>Time in</th>
      <th>Time out</th>
      <th>Total hours</th>
      <th>Homework time</th>
      <th>Literacy time</th>
      <th>Technology time</th>
      <th>Reading specialist time</th>
      <th>Goal</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @after_schools.each do |after_school| %>
      <tr>
        <td><%= after_school.program_id %></td>
        <td><%= after_school.guardian_id %></td>
        <td><%= after_school.date %></td>
        <td><%= after_school.time_in %></td>
        <td><%= after_school.time_out %></td>
        <td><%= after_school.total_hours %></td>
        <td><%= after_school.homework_time %></td>
        <td><%= after_school.literacy_time %></td>
        <td><%= after_school.technology_time %></td>
        <td><%= after_school.reading_specialist_time %></td>
        <td><%= after_school.goal %></td>
        <td><%= link_to 'Show', after_school %></td>
        <td><%= link_to 'Edit', edit_after_school_path(after_school) %></td>
        <td><%= link_to 'Destroy', after_school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New After school', new_after_school_path %>

app/views/after_schools/new.html.erb
<%= render 'form' %>

app/views/after_schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Program:</strong>
  <%= @after_school.program_id %>
</p>

<p>
  <strong>Guardian:</strong>
  <%= @after_school.guardian_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @after_school.date %>
</p>

<p>
  <strong>Time in:</strong>
  <%= @after_school.time_in %>
</p>

<p>
  <strong>Time out:</strong>
  <%= @after_school.time_out %>
</p>

<p>
  <strong>Total hours:</strong>
  <%= @after_school.total_hours %>
</p>

<p>
  <strong>Homework time:</strong>
  <%= @after_school.homework_time %>
</p>

<p>
  <strong>Literacy time:</strong>
  <%= @after_school.literacy_time %>
</p>

<p>
  <strong>Technology time:</strong>
  <%= @after_school.technology_time %>
</p>

<p>
  <strong>Reading specialist time:</strong>
  <%= @after_school.reading_specialist_time %>
</p>

<p>
  <strong>Goal:</strong>
  <%= @after_school.goal %>
</p>

<%= link_to 'Edit', edit_after_school_path(@after_school) %> |
<%= link_to 'Back', after_schools_path %>